### ISSUE TITLE
Clarify with which Windows version xsddiagram is compatible

### ISSUE THREAD

**Issue by 4mitch** [dgis/xsddiagram#12]
Hello! Could you please clarify with which Windows version xsddiagram is compatible. 
I cannot see any diagram on Windows 7 and Microsoft .NET Framework version 2.0 (x64) seems not suitable for Win7. Is there any raplacement for Microsoft .NET Framework version 2.0 ?

**Comment by dgis** [comment]
Hi,
xsddiagram is platform agnostic (x86 or x64) and should work with any Windows versions with at least .NET Framework version 2.0.
Are you sure to not forget to put an element in the diagram?
Regards,
Regis

**Comment by 4mitch** [comment]
Ah! Perfert! I missed that it's needed to press (+) button to get the element.
Looks great! Not even worse than XMLSpy!
Thank you a lot for such useful stuff
