### ISSUE TITLE
case sensitivity badly used

### ISSUE THREAD

**Issue by domicoudin** [dgis/xsddiagram#15]
When in a schema you define two elements with same name but not same case the last one is used in place of first one.
See attached exemple with elements a and A.
In xsddiagram, when showing content of element x we expect to see elements a and b.
Unfortunately we see elements A and b
Version of xsddiagram used is 1.1

![capture](https://user-images.githubusercontent.com/31238625/29556468-3ecf5812-8726-11e7-8900-0a06065f06cd.PNG)

Content of my xsd:

<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="x">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="a"/>
				<xs:element ref="b"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="a">
		<xs:complexType>
			<xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="b">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="A"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="A">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="c"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="c">
		<xs:complexType>
			<xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

**Comment by dgis** [comment]
Thank you domicoudin, I fix it!
