### ISSUE TITLE
Diagram tab is blank when an xsd file is opened.

### ISSUE THREAD

**Issue by manid2** [dgis/xsddiagram#16]
Hi

I am trying to visualize the xsd files in XSDDiagram. I can open the xsd file but diagram tab is blank for any xsd file. Please let me know what I am missing.

Here is the link to sample xsd file i tried to open in this software:
[https://msdn.microsoft.com/en-us/library/dd489283.aspx](url)

**Comment by dgis** [comment]
Hi manid2,

Once you have opened the file, you have to add "PurchaseOrder" to the diagram and then expand the element!

Best regards,
Régis

**Comment by manid2** [comment]
@dgis  Thank you so much, it is working.
