### ISSUE TITLE
Visualization of types

### ISSUE THREAD

**Issue by MarAlder** [dgis/xsddiagram#19]
We are using xsddiagram to support the development of [CPACS](https://github.com/DLR-SL/CPACS). It would help us a lot if the element type was displayed around the elements.

Some proprietary software can do this (e.g., [xmlspy](https://www.altova.com/images/xml-schema-editor.png), but I want to establish xsddiagram as a fast freeware alternative for schema visualization in the CPACS community.

**Comment by dgis** [comment]
Do you mean displaying the type found in the Element tab ("wingSectionsType" in the screenshot), like we display the documentation in the diagram?
![image](https://user-images.githubusercontent.com/620030/66998753-19057880-f0d5-11e9-8c6d-c8066302c345.png)

**Comment by paulushub** [comment]
@dgis Did you view the link he provided to the xmlspy? it is a screenshot.

**Comment by paulushub** [comment]
@MarAlder Here is the view from the currently pending pull request (https://github.com/dgis/xsddiagram/pull/14) also aimed to display types.

![cpacs](https://user-images.githubusercontent.com/809351/67007556-9f947700-f122-11e9-8a7f-0750ee9f0b7a.png)

**Comment by dgis** [comment]
If #14 is what you need, I can add this pull request and set it as optional.

**Comment by MarAlder** [comment]
With an on/off switch it would be very good solution.

**Comment by dgis** [comment]
#14 is now in the main branch, so you can see the type in the diagram by changing the option in the new settings windows! It is not yet available from the command line.
