### ISSUE TITLE
Feature request: Occurrences, real type, and last child indicator are shown in TXT/CSV export; exporting stops when reached the final expanding level on all branches

### ISSUE THREAD

**Issue by TCH68k** [dgis/xsddiagram#22]
So, i put everything into XSD Diagram's exporter, what i needed and made a new patch: http://oscomp.hu/depot/xsddiagram.diff

**Comment by paulushub** [comment]
Exclude binary files from your patch.

**Comment by TCH68k** [comment]
Sorry, Kompare did not listed them and i did not notice. Patchfile has been updated.

**Comment by dgis** [comment]
I succeeded to apply your patch and tested it. All seems to work.
I wonder what the purpose of LASTCHILD, but why not.
I can add it to the main branch and I could make a new version soon.

**Comment by paulushub** [comment]
@dgis Before commit, change the name of the `DiagramTxtRenderer` also, it is still `SVG`
```csharp
public override string Name
{
    get
    {
        return "SVG";
    }
}
```

**Comment by TCH68k** [comment]
@dgis 
Thank you for merging.

The purpose of LASTCHILD is that it marks the line as a last child on a branch.
My current task is to create a specific HTML tree out of XSD files and i solved it by processing the TXT output of XSD Diagram, but since i'm processing the resulting TXT files sequentially (the XSD-s can be enormous, so i did not wanted to double the processing time by collecting everything in the file and rebuild the tree and i could not just integrate that specific HTML output into XSD Diagram, as it would be useless for the users) and i need to show the "lines" which symbolizing the paths, i have to know if a parent will have more siblings after it's children.
I know it's very specific, but it's optional and it can be useful.

**Comment by dgis** [comment]
@paulushub I change that. Thank you.
@TCH68k OK, I understand. Thank you very much for your patch.
I will push your patch today but I will make a new official release 1.3 later.
