### ISSUE TITLE
Something wrong with traversing paths

### ISSUE THREAD

**Issue by smiec** [dgis/xsddiagram#23]
Please check this URL:
http://eudravigilance.ema.europa.eu/XSD/multicacheschemas/MCCI_IN200100UV01.xsd

Below path looks incorrect:
http://eudravigilance.ema.europa.eu/XSD/coreschemas/MCCI_MT200100UV.xsd
It should be:
http://eudravigilance.ema.europa.eu/XSD/multicacheschemas/MCCI_MT200100UV.xsd

Error msg:
"Cannot load the dependency: http://eudravigilance.ema.europa.eu/XSD/coreschemas/MCCI_MT200100UV.xsd, error: System.Net.WebException: Remote server error code: (404) Not found.
   w System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   w System.Net.WebClient.DownloadString(Uri address)
   w XSDDiagram.Schema.LoadSchemaFromUrl(String basePath, String url, String& loadedFilename, String& baseUrl)"

**Comment by dgis** [comment]
Thank you very much to have found this bug.
It should be better now.
You can try the fix with the current build:
https://github.com/dgis/xsddiagram/raw/master/XSDDiagram.exe
