### ISSUE TITLE
Document library dependencies on GNU/Linux (mono)

### ISSUE THREAD

**Issue by mglanville** [dgis/xsddiagram#7]
When first running XSD Diagram on Ubuntu (12.04.5) it raised an unhandled exception:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

This was because I hadn't installed `libmono-winforms2.0-cil`. Installing that library fixed it.

Please could you add a list of dependencies in the ReadMe or elsewhere?

It might also be helpful to catch that exception and explain to the user what's the problem is.

-----

Also (perhaps unrelated to feel free to ignore/move), I get this error:
```
libgluezilla not found. To have webbrowser support, you need libgluezilla installed
```
even though I've installed `libmono-webbrowser2.0-cil`, which claims to contain ["the implementation of the WebControl class based on the Mozilla engine using libgluezilla for CLI 2.0"](https://launchpad.net/ubuntu/precise/+package/libmono-webbrowser2.0-cil).

**Comment by dgis** [comment]
Thanks for the advice, I will update the Readme.txt file, and may be, it misses a dependency in the debian package.
For the "libgluezilla not found", I'm aware of the issue, I only found a workaround by showing the documentation panel as a text panel with mono on Linux. Not great but I never succeeded to make this "libgluezilla" work!

**Comment by dgis** [comment]
No official release yet, but I added the comment in the Readme.txt file.
