### ISSUE TITLE
Multiple 'annotation.documentation' tag support in diagram

### ISSUE THREAD

**Issue by axel3rd** [dgis/xsddiagram#8]
This is a following of #4. This issue is very minor ... and this is for being very pernickety.

Currently, only first _documention_ tag is displayed in diagram (on v1.0), but [annotation](http://www.w3schools.com/xml/el_annotation.asp) tag could contain more that one _documentation_ with [source|lang](http://www.w3schools.com/xml/el_documentation.asp) attributes.

For sample, if you are opening [Maven schema](https://maven.apache.org/xsd/maven-4.0.0.xsd), it explicit the problem.

This snippet represents the use case :

```
<xs:annotation>
  <xs:documentation source="version">1.0</xs:documentation>
  <xs:documentation xml:lang="fr" source="doc">Documentation française</xs:documentation>
  <xs:documentation xml:lang="en" source="doc">English documentation</xs:documentation>
  <xs:documentation>This feature is wonderful !</xs:documentation>
</xs:annotation>
```

Perhaps these attributes could be used for produce : 

```
 1.0 (version)
 Documentation française (fr, doc)
 English documentation (en, doc)
 This feature is wonderful !
```

It is better to have the source at the end, because could a an URI so a little long text.

**Comment by dgis** [comment]
Thank you, I will add it for the next version;-)

**Comment by dgis** [comment]
It should work now!

**Comment by axel3rd** [comment]
Thank you !
