### ISSUE TITLE
Export SVG: Without page

### ISSUE THREAD

**Issue by kouinkouin** [dgis/xsddiagram#9]
Hello,

When I open a SVG (exported from xsddiagram) with Inkscape, Inkscape sees a empty page, and zooms on the empty page, so we don't see the diagam at the first time.
By zooming out, I see the diagram, so it's not a critical issue ;-) .

Here an example to test with Inkscape: [aze.svg.zip](https://github.com/dgis/xsddiagram/files/153151/aze.svg.zip)

I'm on Debian Jessie, Inkscape 0.91, and xsddiagram 1.0-1 (from official Debian repo).

**Comment by dgis** [comment]
Thank you for the bug report, I commit the fix.
It is a lot better when opening in Firefox too !
It will be in the next release. But you can already download it in the repository :-)
https://github.com/dgis/xsddiagram/raw/master/XSDDiagram.exe

**Comment by dgis** [comment]
I close the isssue

**Comment by kouinkouin** [comment]
Woohoo ! Fixed in less 2 hours !
I will wait the new version in official Debian repositories (I am on Debian sid and not Jessie), but thanks a lot for reactivity !
I will confirm the fix when I see the package is updated :) .

**Comment by dgis** [comment]
It can take time to get it in Debian!
